# Generated by Django 5.1.6 on 2025-07-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchased_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_purchased', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('main_category', models.CharField(choices=[('Food', 'Food'), ('Treat', 'Treat'), ('Health', 'Health'), ('Grooming', 'Grooming'), ('Wellness', 'Wellness')], max_length=50)),
                ('sub_category', models.CharField(choices=[('Dry', 'Dry'), ('Wet', 'Wet'), ('Raw', 'Raw'), ('Dental', 'Dental'), ('Training', 'Training'), ('Vitamins', 'Vitamins'), ('Tick & Flea', 'Tick & Flea'), ('Recovery Collars', 'Recovery Collars'), ('Shampoo & Conditioner', 'Shampoo & Conditioner'), ('Pet Brush', 'Pet Brush'), ('Spritz & Wipes', 'Spritz & Wipes'), ('Toys', 'Toys'), ('Beds & Kennels', 'Beds & Kennels'), ('Harness & Leashes', 'Harness & Leashes')], max_length=50)),
                ('product_code', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('update', 'Updated')], max_length=10)),
                ('quantity_changed', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.product')),
            ],
        ),
    ]
